Hello Microverse project
DjibrilM/hello-microverse-project pull request #1
Opened 2023-04-25 20:16 UTC by DjibrilM

## Hello Microverse project
 ###  in this project I
     
1.  added   Linters 
2.  added an HTML file with a header inside of it
3.  add a CSS file with style for the header

2023-04-25 20:50 UTC, vickymarz requested changes
Hi @DjibrilM, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- All tests are passing ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] You did well trying to setup linters but your linters is not showing the green check mark because the github workflows for linters is not present in your file. Kindly check the step by step procedure of setting up linters carefully so that your linters can pass accordingly. Here is a [link](https://github.com/microverseinc/linters-config/tree/master/html-css) to the linters setup 

- [ ] Good job on your commit message 👍🏽 .Kindly endure you always capitalize the first letter of your commit messages. E.g Add linters

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 20:50 UTC, vickymarz commented on README.md
> +# 📖 Microverse Hello project <a name="about-project"></a>
- [ ] You should have a README file that contains information about your project , make sure you use the README template provided by microverse and customize it to meet the requirement. You can find it [here](https://github.com/microverseinc/readme-template) 

Make sure you fill up all the sections of the readme (FAQ section is optional) with informations about the project so that your repo can look professional 👍🏽

2023-04-25 20:50 UTC, vickymarz commented on index.html
> +<h1>Hello Microverse!</h1>
- [ ] Please make sure you use the boiler plate for HTML to create your html page. What you have done is not a valid HTML . You can learn more about HTML [here](https://www.w3schools.com/html/)

2023-04-26 08:17 UTC, DjibrilM commented on index.html
> +<h1>Hello Microverse!</h1>
Thanks for this, I was confused since it was mentioned that we only put on a header, but now its problem is now solved

2023-04-27 00:02 UTC, braincee requested changes
Hello @DjibrilM , I am @braincee your Code Reviewer

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


![so-close](https://user-images.githubusercontent.com/78104544/225492039-ed22bba9-481a-489f-ae04-74623970af20.gif)

HIGHLIGHTS
------

 - GitHub flow rightfully used ✅
 - Meaningful title and summary for PR ✅
 - Professional README.md file ✅
 - No linter errors ✅

REQUIRED CHANGES ♻️
------
**_Please check the comments under the review._**

OPTIONAL CHANGES
--------
**_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @braincee in your question so I can receive the notification.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

----

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 00:02 UTC, braincee commented on .gitignore
> +/test.md
Please ensure to add the `test.md` file per the project requirements. 😄 
The `test.md` file should have the text `This file should be ignored by git.` 😄

2023-04-27 10:47 UTC, DjibrilM commented on .gitignore
> +/test.md
I am a bit confused with the comment should remove the test.md file in  gitignore

2023-04-27 17:50 UTC, wickathou approved these changes
Hi @DjibrilM , 

Your project is complete!!

There is nothing else to say other than... it's time to merge it

# Congratulations! 🎉 

## Highlights
- Clear Readme details
- All linters working properly
- Descriptive PR

## Optional suggestions
- [ ] For coming pull requests, please add more descriptive titles, so for example, instead of `Hello Microverse Project` you could use `PR - Code Review - Implementation of linters and documentation`

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 17:50 UTC, wickathou commented on README.md
> +<!-- LICENSE -->
[Optional] Consider removing the commented indications on the readme file since they are not necessary

2023-04-27 17:50 UTC, wickathou commented on .gitignore
> +/test.md
[Optional] To avoid issues with relative paths, you could also define these entries in the following way:
`node_modules/`
`test.md`

2023-04-27 17:50 UTC, wickathou commented on .gitignore
> +/package-lock.json
[Optional] To avoid issues when collaborators try to run `npm install`, consider removing package-lock.json from the .gitignore list, as this file serves an important role by informing to the package manager the installation sequence of the all the modules.

For more info check
https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

2023-04-27 17:50 UTC, wickathou commented on README.md
> +    <li><a href="https://reactjs.org/">CSS</a></li>
[Optional] These two links refer to HTML and CSS but the href is directed to reactjs.org, consider removing the link tags or updating the href to a relevant web resource for HTML and CSS

2023-04-27 17:50 UTC, wickathou commented on index.html
> +</head>
[Optional] It seems that you forgot to add the `<link>` tag to connect your style.css file to your HTML. Consider updating it to connect them by using `<link rel="stylesheet" href="style.css">`

2023-04-27 17:50 UTC, wickathou commented on package.json
> +  },
[Optional] To make the process of fixing linter issues easier, consider adding the following scripts to your package.json:
```
"css-lint": "npx stylelint \"**/*.{css,scss}\"",
"css-lint-fix": "npx stylelint \"**/*.{css,scss}\" --fix"
```
That will allow you to see lint issues by simple running the command `npm run css-lint` to see all lint issues in your CSS and using `npm run css-lint-fix` will automatically fix the easy to solve problems with your CSS

2023-04-27 17:51 UTC, wickathou approved these changes

2023-05-02 07:19 UTC, merged